"""Generate `results_numbers.tex` with all manuscript headline numbers as LaTeX macros.

Reads from outputs/{irt, baselines}/ and writes a single .tex file that can be
\\input{}-ed into the manuscript. Whenever new inference completes and the IRT
pipeline is re-run, re-run this script and re-compile the manuscript -- all
numbers update automatically.
"""

from __future__ import annotations

import json
import csv
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
IRT_DIR = REPO_ROOT / "outputs" / "irt"
BASE_DIR = REPO_ROOT / "outputs" / "baselines"
OUT_PATH = REPO_ROOT / "outputs" / "results_numbers.tex"

_DIGIT_WORDS = {
    "0": "zero", "1": "one", "2": "two", "3": "three", "4": "four",
    "5": "five", "6": "six", "7": "seven", "8": "eight", "9": "nine",
}


def _safe_macro_name(raw: str) -> str:
    """Convert a model/subject identifier into a LaTeX-legal macro suffix.

    LaTeX command names allow only letters, so we strip punctuation and
    convert digits into their spelled-out form.
    """
    out_chars: list[str] = []
    for ch in raw:
        if ch.isalpha():
            out_chars.append(ch)
        elif ch.isdigit():
            out_chars.append(_DIGIT_WORDS[ch].capitalize())
        # else: skip "-", ".", "/", spaces, etc.
    return "".join(out_chars)


def _sci(x: float, digits: int = 2) -> str:
    """Format a (possibly big) number compactly for LaTeX math context.

    Numbers in [10, 1e4) are printed with one decimal; numbers outside this
    range are rendered in scientific notation as ``$a \\times 10^{b}$``.
    """
    ax = abs(x)
    if ax == 0:
        return "0"
    if 10 <= ax < 1e4:
        return f"{x:.0f}"
    if ax < 10 and ax >= 0.01:
        return f"{x:.{digits}f}"
    # Scientific notation
    import math
    exp = int(math.floor(math.log10(ax)))
    mant = x / (10 ** exp)
    return f"${mant:.2f}{{\\times}}10^{{{exp}}}$"


def _read_json(path: Path) -> dict:
    with path.open() as fh:
        return json.load(fh)


def _read_csv(path: Path) -> list[dict]:
    with path.open() as fh:
        return list(csv.DictReader(fh))


def main() -> None:
    fit_summary = _read_json(IRT_DIR / "fit_summary.json")
    headline = _read_json(IRT_DIR / "headline_findings.json")

    lines: list[str] = [
        "% Auto-generated by analysis/export_manuscript_numbers.py -- do not edit.",
        "% Re-run that script after every fresh IRT fit to refresh.",
        "",
    ]

    corpus = fit_summary["corpus"]
    lines += [
        rf"\newcommand{{\NTestTakers}}{{{corpus['n_subjects']}}}",
        rf"\newcommand{{\NItems}}{{{corpus['n_items']:,}}}",
        rf"\newcommand{{\NObservations}}{{{corpus['n_observations']:,}}}",
        rf"\newcommand{{\NPathologies}}{{14}}",
    ]

    for raw_name, n in corpus["obs_per_subject"].items():
        macro = _safe_macro_name(raw_name)
        lines.append(rf"\newcommand{{\NObs{macro}}}{{{n:,}}}")
    for raw_name, acc in corpus["raw_accuracy_per_subject"].items():
        macro = _safe_macro_name(raw_name)
        lines.append(rf"\newcommand{{\Acc{macro}}}{{{acc*100:.1f}\%}}")

    best = headline["best_holdout_model"]
    lines += [
        rf"\newcommand{{\BestModel}}{{{best}}}",
        rf"\newcommand{{\BestHoldoutNLL}}{{{float(headline['best_holdout_nll_per_obs']):.3f}}}",
    ]
    if "best_baseline_model" in headline:
        bb = headline["best_baseline_model"]
        bb_pretty = bb.replace("_", "-")
        lines += [
            rf"\newcommand{{\BestBaselineModel}}{{{bb_pretty}}}",
            rf"\newcommand{{\BestBaselineNLL}}{{{float(headline['best_baseline_nll_per_obs']):.3f}}}",
        ]

    for fit_row in headline["model_fit_table"]:
        name = fit_row["model"]
        macro = _safe_macro_name(name.capitalize())
        lines += [
            rf"\newcommand{{\Nll{macro}}}{{{float(fit_row['test_nll_per_obs']):.3f}}}",
            rf"\newcommand{{\Bic{macro}}}{{{_sci(float(fit_row['BIC']))}}}",
            rf"\newcommand{{\Params{macro}}}{{{int(fit_row['n_params']):,}}}",
        ]
        if fit_row.get("test_f1_positive"):
            lines.append(
                rf"\newcommand{{\Fone{macro}}}{{{float(fit_row['test_f1_positive']):.3f}}}"
            )
        if fit_row.get("test_auc"):
            lines.append(
                rf"\newcommand{{\Auc{macro}}}{{{float(fit_row['test_auc']):.3f}}}"
            )
        if fit_row.get("test_accuracy"):
            lines.append(
                rf"\newcommand{{\AccHO{macro}}}{{{float(fit_row['test_accuracy']):.3f}}}"
            )

    disc = headline["discrimination_spread_within_tier"]
    for tier, val in disc.items():
        lines.append(rf"\newcommand{{\DiscSpread{tier.capitalize()}}}{{{float(val['p10_to_p90_range']):.1f}}}")

    if headline.get("top_dif_by_age"):
        first = headline["top_dif_by_age"][0]
        lines += [
            rf"\newcommand{{\TopDIFAgePath}}{{{first[0]}}}",
            rf"\newcommand{{\TopDIFAgeSpread}}{{{float(first[1]):.3f}}}",
        ]
    if headline.get("top_dif_by_sex"):
        first = headline["top_dif_by_sex"][0]
        lines += [
            rf"\newcommand{{\TopDIFSexPath}}{{{first[0]}}}",
            rf"\newcommand{{\TopDIFSexSpread}}{{{float(first[1]):.3f}}}",
        ]

    lines.append(rf"\newcommand{{\SpearmanBestAgg}}{{{float(headline['spearman_best_irt_vs_aggregate']):.2f}}}")

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"✓ wrote {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()

